//
//  DBColorNames.swift
//  ddoyac
//
//  Created by SEUNGWON YANG on 2021/05/04.
//

import Foundation
import UIKit

class DBColorNames {
    
     
    static let colorMap: [String : Int] = [
            "cloudy blue, blue, gray, white": 0xacc2d9,
            "dark pastel green, green": 0x56ae57,
            "dust, brown": 0xb2996e,
            "electric lime, green": 0xa8ff04,
            "fresh green, green": 0x69d84f,
            "light eggplant, purple, pink": 0x894585,
            "nasty green, green": 0x70b23f,
            "really light blue, blue, white, gray": 0xd4ffff,
            "tea, green": 0x65ab7c,
            "warm purple, purple, pink": 0x952e8f,
            "yellowish tan, yellow, white, brown": 0xfcfc81,
            "cement, gray": 0xa5a391,
            "dark grass green, green": 0x388004,
            "dusty teal, blue, green, blue, gray": 0x4c9085,
            "grey teal, green, blue, gray": 0x5e9b8a,
            "macaroni and cheese, red, yellow, brown": 0xefb435,
            "pinkish tan, red, yellow, pink, brown": 0xd99b82,
            "spruce, green": 0x0a5f38,
            "strong blue, blue, black": 0x0c06f7,
            "toxic green, green": 0x61de2a,
            "windows blue, blue, gray ": 0x3778bf,
            "blue blue, blue": 0x2242c7,
            "blue with a hint of purple, blue, purple": 0x533cc6,
            "booger, green": 0x9bb53c,
            "bright sea green, green, white, blue": 0x05ffa6,
            "dark green blue, green, blue": 0x1f6357,
            "deep turquoise, green, gray, blue": 0x017374,
            "green teal, green": 0x0cb577,
            "strong pink, pink, red": 0xff0789,
            "bland, brown, gray, brown": 0xafa88b,
            "deep aqua, green, gray, blue": 0x08787f,
            "lavender pink, pink, purple": 0xdd85d7,
            "light moss green, green": 0xa6c875,
            "light seafoam green, green, white": 0xa7ffb5,
            "olive yellow, yellow, green, brown, yellow": 0xc2b709,
            "pig pink, pink, red": 0xe78ea5,
            "deep lilac, pink, purple": 0x966ebd,
            "desert, brown, yellow": 0xccad60,
            "dusty lavender, purple, pink, gray": 0xac86a8,
            "purpley grey, gray, purpley, pink": 0x947e94,
            "purply, purply, pink": 0x983fb2,
            "candy pink, pink": 0xff63e9,
            "light pastel green, green, white": 0xb2fba5,
            "boring green, green": 0x63b365,
            "kiwi green, green": 0x8ee53f,
            "light grey green, green, gray, white": 0xb7e1a1,
            "orange pink, red, brown": 0xff6f52,
            "tea green, green, white": 0xbdf8a3,
            "very light brown, brown, white, yellow": 0xd3b683,
            "egg shell, yellow, white": 0xfffcc4,
            "eggplant purple, purple, pink, red": 0x430541,
            "powder pink, pink": 0xffb2d0,
            "reddish grey, red, purple, brown, gray": 0x997570,
            "baby shit brown, brown, red, yellow": 0xad900d,
            "liliac, purple, pink": 0xc48efd,
            "stormy blue, blue, black, gray":0x507b9c,
            "ugly brown, brown, yellow": 0x7d7103,
            "custard, yellow, white": 0xfffd78,
            "darkish pink, pink, red": 0xda467d,
            "deep brown, brown, red": 0x410200,
            "greenish beige, green, white, yellow":0xc9d179,
            "manilla, yellow, white": 0xfffa86,
            "off blue, blue, black, gray": 0x5684ae,
            "battleship grey, gray, blue, black": 0x6b7c85,
            "browny green, brown, green": 0x6f6c0a,
            "bruise, pink, purple, red": 0x7e4071,
            "kelley green, green": 0x009337,
            "sickly yellow, green, white": 0xd0e429,
            "sunny yellow, yellow, white": 0xfff917,
            "azul, blue": 0x1d5dec,
            "darkgreen, green, blue": 0x054907,
            "green/yellow, green": 0xb5ce08,
            "lichen, green, gray": 0x8fb67b,
            "light light green, green, white": 0xc8ffb0,
            "pale gold, yellow, brown": 0xfdde6c,
            "sun yellow, yellow, brown": 0xffdf22,
            "tan green, green, gray": 0xa9be70,
            "burple, purple, blue": 0x6832e3,
            "butterscotch, red, brown, yellow": 0xfdb147,
            "toupe, brown, gray, ": 0xc7ac7d,
            "dark cream, yellow, white": 0xfff39a,
            "indian red, red, brown, purple": 0x850e04,
            "light lavendar, pink, purple": 0xefc0fe,
            "poison green, green, white": 0x40fd14,
            "baby puke green, green, gray": 0xb6c406,
            "bright yellow green, green": 0x9dff00,
            "charcoal grey, black, gray, green": 0x3c4142,
            "squash, brown, red, yellow": 0xf2ab15,
            "cinnamon, brown, red": 0xac4f06,
            "light pea green, green, white, gray": 0xc4fe82,
            "radioactive green, green": 0x2cfa1f,
            "raw sienna brown, red, yellow": 0x9a6200,
            "baby purple, purple, pink": 0xca9bf7,
            "cocoa, brown, red": 0x875f42,
            "light royal blue, blue, black": 0x3a2efe,
            "orangeish, red, brown": 0xfd8d49,
            "rust brown, brown, red": 0x8b3103,
            "sand brown, brown, white, gray": 0xcba560,
            "swamp, green, gray": 0x698339,
            "tealish green, green": 0x0cdc73,
            "burnt siena, brown, red": 0xb75203,
            "camo, green, gray": 0x7f8f4e,
            "dusk blue, blue, gray, black": 0x26538d,
            "fern, green, gray": 0x63a950,
            "old rose, pink, purple": 0xc87f89,
            "pale light green, green, white": 0xb1fc99,
            "peachy pink, pink, red": 0xff9a8a,
            "rosy pink, pink, red": 0xf6688e,
            "light bluish green, green, white": 0x76fda8,
            "light bright green, green": 0x53fe5c,
            "light neon green, green": 0x4efd54,
            "light seafoam, green, white": 0xa0febf,
            "tiffany blue, green, blue, white": 0x7bf2da,
            "washed out green, green, white": 0xbcf5a6,
            "browny orange, brown, red": 0xca6b02,
            "nice blue, blue, gray, black": 0x107ab0,
            "sapphire, blue, black": 0x2138ab,
            "greyish teal, green, gray": 0x719f91,
            "orangey yellow, yellowl, brown": 0xfdb915,
            "parchment, yellow, white": 0xfefcaf,
            "straw, yellow, white": 0xfcf679,
            "very dark brown, black, red": 0x1d0200,
            "terracota, brown, red": 0xcb6843,
            "ugly blue, blue, gray, black": 0x31668a,
            "clear blue, blue": 0x247afd,
            "creme, yellow, white": 0xffffb6,
            "foam green, green, white": 0x90fda9,
            "grey/green, green, gray": 0x86a17d,
            "light gold, yellow, white, brown": 0xfddc5c,
            "seafoam blue, green, blue, white, gray": 0x78d1b6,
            "topaz, green, blue": 0x13bbaf,
            "violet pink, pink, purple": 0xfb5ffc,
            "wintergreen, green, white": 0x20f986,
            "yellow tan, yellow, brown": 0xffe36e,
            "dark fuchsia, purple, red": 0x9d0759,
            "indigo blue, blue, black": 0x3a18b1,
            "light yellowish green, green, whtie": 0xc2ff89,
            "pale magenta, pink, purple": 0xd767ad,
            "rich purple, purple, red": 0x720058,
            "sunflower yellow, yellow, brown": 0xffda03,
            "green/blue, green, blue": 0x01c08d,
            "leather, brown, red": 0xac7434,
            "racing green, green, blue": 0x014600,
            "vivid purple, purple": 0x9900fa,
            "dark royal blue, blue, black, gray": 0x02066f,
            "hazel, brown, red": 0x8e7618,
            "muted pink, pink, gray, purple": 0xd1768f,
            "booger green, green": 0x96b403,
            "canary, yellow, white": 0xfdff63,
            "cool grey, grey": 0x95a3a6,
            "dark taupe, brown": 0x7f684e,
            "darkish purple, purple, red": 0x751973,
            "true green, green": 0x089404,
            "coral pink, red, pink": 0xff6163,
            "dark sage, green, gray": 0x598556,
            "dark slate blue, blue, black, gray": 0x214761,
            "flat blue, blue, gray, black": 0x3c73a8,
            "mushroom, brown, gray, white": 0xba9e88,
            "rich blue, blue": 0x021bf9,
            "dirty purple, purple, brown, gray": 0x734a65,
            "greenblue, green, blue": 0x23c48b,
            "icky green, green": 0x8fae22,
            "light khaki, green, white": 0xe6f2a2,
            "warm blue, blue, gray": 0x4b57db,
            "dark hot pink, red, pink": 0xd90166,
            "deep sea blue, blue, gray, black": 0x015482,
            "carmine, red, brown": 0x9d0216,
            "dark yellow green, green, gray": 0x728f02,
            "green again, green":0x16b3f,
            "pale peach, yellow, white": 0xffe5ad,
            "plum purple, purple, red": 0x4e0550,
            "golden rod, yellow, brown": 0xf9bc08,
            "neon red, red": 0xff073a,
            "old pink, pink, gray, purple": 0xc77986,
            "very pale blue, blue, white, gray": 0xd6fffe,
            "blood orange, red, brown": 0xfe4b03,
            "grapefruit, red, brown": 0xfd5956,
            "sand yellow, yellow, brown": 0xfce166,
            "clay brown, brown": 0xb2713d,
            "dark blue grey, gray, blue, black": 0x1f3b4d,
            "flat green, green": 0x699d4c,
            "light green blue, green, white": 0x56fca2,
            "warm pink, pink, red, purple": 0xfb5581,
            "dodger blue, blue, gray, white": 0x3e82fc,
            "gross green, green": 0xa0bf16,
            "ice, white, blue": 0xd6fffa,
            "metallic blue, blue, black, gray": 0x4f738e,
            "pale salmon, yellow, brown, pink": 0xffb19a,
            "sap green, green": 0x5c8b15,
            "algae, green": 0x54ac68,
            "bluey grey, gray": 0x89a0b0,
            "greeny grey, green, gray": 0x7ea07a,
            "highlighter green, green, white": 0x1bfc06,
            "light light blue, white, blue": 0xcafffb,
            "light mint, white, green": 0xb6ffbb,
            "raw umber, brown, red": 0xa75e09,
            "vivid blue, blue": 0x152eff,
            "deep lavender, purple, pink": 0x8d5eb7,
            "dull teal, green, gray": 0x5f9e8f,
            "light greenish blue, green, white": 0x63f7b4,
            "mud green, green": 0x606602,
            "pinky, pink, purple": 0xfc86aa,
            "red wine, red, purple": 0x8c0034,
            "shit green, green": 0x758000,
            "tan brown, brown, red": 0xab7e4c,
            "darkblue, blue, black": 0x030764,
            "rosa, pink, purple": 0xfe86a4,
            "lipstick, red, purple": 0xd5174e,
            "pale mauve, pink, purple, white": 0xfed0fc,
            "claret, brown, red, purple": 0x680018,
            "dandelion, yellow, brown": 0xfedf08,
            "orangered, red": 0xfe420f,
            "poop green, green": 0x6f7c00,
            "ruby, red, purple": 0xca0147,
            "dark, green, black, blue, gray": 0x1b2431,
            "greenish turquoise, green, white, blue": 0x00fbb0,
            "pastel red, red, brown": 0xdb5856,
            "piss yellow, yellow, green, brown": 0xddd618,
            "bright cyan, blue, white": 0x41fdfe,
            "dark coral, red, brown": 0xcf524e,
            "algae green, green": 0x21c36f,
            "darkish red, red, brown": 0xa90308,
            "reddy brown, brown, red": 0x6e1005,
            "blush pink, pink, purple": 0xfe828c,
            "camouflage green, green, gray": 0x4b6113,
            "lawn green, green": 0x4da409,
            "putty, gray, brown": 0xbeae8a,
            "vibrant blue, blue": 0x0339f8,
            "dark sand, brown": 0xa88f59,
            "purple/blue, blue, purple": 0x5d21d0,
            "saffron, yellow, brown": 0xfeb209,
            "twilight, blue, black, gray": 0x4e518b,
            "warm brown, brown": 0x964e02,
            "bluegrey gray, white, blue": 0x85a3b2,
            "bubble gum pink, pink": 0xff69af,
            "duck egg blue, white, blue, gray": 0xc3fbf4,
            "greenish cyan, green, white": 0x2afeb7,
            "petrol, green, blue, gray": 0x005f6a,
            "royal, blue, black": 0x0c1793,
            "butter, yellow, white": 0xffff81,
            "dusty orange, red, brown": 0xf0833a,
            "off yellow, yellow, brown": 0xf1f33f,
            "pale olive green, green, gray": 0xb1d27b,
            "orangish, red, brown, yellow": 0xfc824a,
            "leaf, green": 0x71aa34,
            "light blue grey, blue, grey, purple, white": 0xb7c9e2,
            "dried blood, brown, red, purple": 0x4b0101,
            "lightish purple, purple, pink": 0xa552e6,
            "rusty red, brown, red": 0xaf2f0d,
            "lavender blue, purple, pink": 0x8b88f8,
            "light grass green, green": 0x9af764,
            "light mint green, green, white": 0xa6fbb2,
            "sunflower, yellow, brown": 0xffc512,
            "velvet, purple, red": 0x750851,
            "brick orange, brown, red": 0xc14a09,
            "lightish red, red, brown": 0xfe2f4a,
            "pure blue, blue": 0x0203e2,
            "twilight blue, black, blue": 0x0a437a,
            "violet red, purple, pink": 0xa50055,
            "yellowy brown, brown, yellow": 0xae8b0c,
            "carnation, pink, red": 0xfd798f,
            "muddy yellow, brown": 0xbfac05,
            "dark seafoam green, green": 0x3eaf76,
            "deep rose, pink, red, purple": 0xc74767,
            "dusty red, red, brown": 0xb9484e,
            "grey/blue, gray, blue, black": 0x647d8e,
            "lemon lime, green, white": 0xbffe28,
            "purple/pink, pink, purple": 0xd725de,
            "brown yellow, brown, red": 0xb29705,
            "purple brown, brown, red": 0x673a3f,
            "wisteria, purple, pink": 0xa87dc2,
            "banana yellow, yellow, white": 0xfafe4b,
            "lipstick red, red": 0xc0022f,
            "water blue, blue": 0x0e87cc,
            "brown grey, grey, brown": 0x8d8468,
            "vibrant purple, purple, pink": 0xad03de,
            "baby green, green, white": 0x8cff9e,
            "barf green, green": 0x94ac02,
            "eggshell blue, blue, white": 0xc4fff7,
            "sandy yellow, yellow, white, brown": 0xfdee73,
            "cool green, green": 0x33b864,
            "pale, white, yellow, white, gray, brown": 0xfff9d0,
            "blue/grey, gray, blue": 0x758da3,
            "hot magenta, pink": 0xf504c9,
            "greyblue, blue, gray": 0x77a1b5,
            "purpley, purple, pink": 0x8756e4,
            "baby shit green, green": 0x889717,
            "brownish pink, pink, brown, red": 0xc27e79,
            "dark aquamarine, green, blue": 0x017371,
            "diarrhea, brown, red": 0x9f8303,
            "light mustard, yellow, brown": 0xf7d560,
            "pale sky blue, blue, white, gray": 0xbdf6fe,
            "turtle green, green": 0x75b84f,
            "bright olive, green": 0x9cbb04,
            "dark grey blue, blue, grey, green, black": 0x29465b,
            "greeny brown, brown, red": 0x696006,
            "lemon green, green": 0xadf802,
            "light periwinkle, purple, gray, white": 0xc1c6fc,
            "seaweed green, green": 0x35ad6b,
            "sunshine yellow, yellow, white": 0xfffd37,
            "ugly purple, purple, pink": 0xa442a0,
            "medium pink, pink, purple": 0xf36196,
            "puke brown, brown, red": 0x947706,
            "very light pink white, pink, white": 0xfff4f2,
            "viridian, green": 0x1e9167,
            "bile, green, yellow": 0xb5c306,
            "faded yellow, yellow, white, brown": 0xfeff7f,
            "very pale green, green, gray, white": 0xcffdbc,
            "vibrant green, green": 0x0add08,
            "bright lime, green": 0x87fd05,
            "spearmint, green": 0x1ef876,
            "light aquamarine, green, white": 0x7bfdc7,
            "light sage, green, gray, white": 0xbcecac,
            "yellowgreen, green": 0xbbf90f,
            "baby poo, brown": 0xab9004,
            "dark seafoam, green": 0x1fb57a,
            "deep teal, green, blue, gray": 0x00555a,
            "heather, purple, gray, pink": 0xa484ac,
            "rust orange, brown, red": 0xc45508,
            "dirty blue, blue, gray, white": 0x3f829d,
            "fern green, green": 0x548d44,
            "bright lilac, purple, pink": 0xc95efb,
            "weird green, green, white": 0x3ae57f,
            "peacock blue, blue, gray, black": 0x016795,
            "avocado green, green": 0x87a922,
            "faded orange, red, brown": 0xf0944d,
            "grape purple, purple, red": 0x5d1451,
            "hot green, green, white": 0x25ff29,
            "lime yellow, green, yellow, white": 0xd0fe1d,
            "mango, red, brown": 0xffa62b,
            "shamrock, green": 0x01b44c,
            "bubblegum, pink": 0xff6cb5,
            "purplish brown, brown, red, purple, gray": 0x6b4247,
            "vomit yellow, yellow, brown": 0xc7c10c,
            "pale cyan, blue, white, gray": 0xb7fffa,
            "key lime, green, white": 0xaeff6e,
            "tomato red, red": 0xec2d01,
            "lightgreen, green": 0x76ff7b,
            "merlot, brown, red, purple": 0x730039,
            "night blue, blue, black": 0x040348,
            "purpleish pink, pink, purple": 0xdf4ec8,
            "apple, green": 0x6ecb3c,
            "baby poop green, green, brown": 0x8f9805,
            "green apple, green": 0x5edc1f,
            "heliotrope, pink, purple": 0xd94ff5,
            "yellow/green, green, white": 0xc8fd3d,
            "almost black, black": 0x070d0d,
            "cool blue, blue, gray, white": 0x4984b8,
            "leafy green, green": 0x51b73b,
            "mustard brown, brown": 0xac7e04,
            "dusk, blue, gray, purple": 0x4e5481,
            "dull brown, brown, gray": 0x876e4b,
            "frog green, green": 0x58bc08,
            "vivid green, green": 0x2fef10,
            "bright light green, green": 0x2dfe54,
            "fluro green, green": 0x0aff02,
            "kiwi, green, white": 0x9cef43,
            "seaweed, green": 0x18d17b,
            "navy green, green": 0x35530a,
            "ultramarine blue, blue": 0x1805db,
            "iris, blue, purple, white, gray": 0x6258c4,
            "pastel orange, red, brown": 0xff964f,
            "yellowish orange, red, brown": 0xffab0f,
            "perrywinkle, purple, blue, gray, white": 0x8f8ce7,
            "tealish, green, blue": 0x24bca8,
            "dark plum, purple, black, red": 0x3f012c,
            "pear, green, white": 0xcbf85f,
            "pinkish orange, red": 0xff724c,
            "midnight purple, black, purple": 0x280137,
            "light urple, purple": 0xb36ff6,
            "dark mint, green": 0x48c072,
            "greenish tan, green, gray, white": 0xbccb7a,
            "light burgundy, red, brown, purple": 0xa8415b,
            "turquoise blue, blue, white": 0x06b1c4,
            "ugly pink, pink, red, purple": 0xcd7584,
            "sandy, yellow, brown": 0xf1da7a,
            "electric pink, pink, purple, red": 0xff0490,
            "muted purple, purple, gray, pink": 0x805b87,
            "mid green, green": 0x50a747,
            "greyish, gray, white, brown": 0xa8a495,
            "neon yellow, green, white": 0xcfff04,
            "banana, yellow, white": 0xffff7e,
            "carnation pink, pink, purple": 0xff7fa7,
            "tomato, red, brown": 0xef4026,
            "sea, green": 0x3c9992,
            "muddy brown, brown": 0x886806,
            "turquoise green, green, white": 0x04f489,
            "buff, yellow, white": 0xfef69e,
            "fawn, brown, gray, white": 0xcfaf7b,
            "muted blue, blue, gray": 0x3b719f,
            "pale rose, pink, red, white": 0xfdc1c5,
            "dark mint green, green": 0x20c073,
            "amethyst, purple, pink": 0x9b5fc0,
            "blue/green, green, gray, blue": 0x0f9b8e,
            "chestnut, brown": 0x742802,
            "darker pink, pink, purple":0xc4387f,
            "sick green, green": 0x9db92c,
            "pea, green, green": 0xa4bf20,
            "rusty orange, red, brown": 0xcd5909,
            "stone, gray": 0xada587,
            "rose red, red": 0xbe013c,
            "pale aqua, blue, white": 0xb8ffeb,
            "deep orange, red, brown": 0xdc4d01,
            "earth, brown": 0xa2653e,
            "mossy green, green": 0x638b27,
            "grassy green, green": 0x419c03,
            "pale lime green, green, white": 0xb1ff65,
            "light grey blue, gray, blue, white": 0x9dbcd4,
            "pale grey, white, gray": 0xfdfdfe,
            "asparagus, green": 0x77ab56,
            "blueberry, blue, black": 0x464196,
            "purple red, red, purple, pink": 0x990147,
            "pale lime, green, whtie": 0xbefd73,
            "greenish teal, green": 0x32bf84,
            "caramel, brown": 0xaf6f09,
            "deep magenta, red, purple, pink": 0xa0025c,
            "light peach, yellow, pink": 0xffd8b1,
            "milk chocolate, brown": 0x7f4e1e,
            "ocher, brown": 0xbf9b0c,
            "off green, green": 0x6ba353,
            "purply pink, pink, purple": 0xf075e6,
            "lightblue, blue, white, gray": 0x7bc8f6,
            "dusky blue, blue, gray": 0x475f94,
            "golden, yellow, brown": 0xf5bf03,
            "light beige, yellow, white": 0xfffeb6,
            "butter yellow, yellow, white": 0xfffd74,
            "dusky purple, purple, pink": 0x895b7b,
            "french blue, blue, gray": 0x436bad,
            "ugly yellow, yellow, brown": 0xd0c101,
            "greeny yellow, green, white": 0xc6f808,
            "orangish red, red": 0xf43605,
            "shamrock green, green": 0x02c14d,
            "orangish brown, brown": 0xb25f03,
            "tree green, green": 0x2a7e19,
            "deep violet, purple, red": 0x490648,
            "gunmetal, gray, green": 0x536267,
            "blue/purple, blue, black": 0x5a06ef,
            "cherry, red": 0xcf0234,
            "sandy brown, brown": 0xc4a661,
            "warm grey, grey, white": 0x978a84,
            "dark indigo, blue, black": 0x1f0954,
            "midnight, black": 0x03012d,
            "bluey green, green": 0x2bb179,
            "grey pink, pink, purple": 0xc3909b,
            "soft purple, purple, pink": 0xa66fb5,
            "blood, brown ,red": 0x770001,
            "brown red, brown, red": 0x922b05,
            "medium grey, gray, white": 0x7d7f7c,
            "berry, red, brown, purple": 0x990f4b,
            "poo, brown": 0x8f7303,
            "purpley pink, pink, purple, red": 0xc83cb9,
            "light salmon, pink, red, white": 0xfea993,
            "snot, green": 0xacbb0d,
            "easter purple, purple, pink": 0xc071fe,
            "light yellow green, green, white": 0xccfd7f,
            "dark navy blue, blue, black": 0x00022e,
            "drab, brown, green": 0x828344,
            "light rose, pink, red, white, purple": 0xffc5cb,
            "rouge, purple, red, pink": 0xab1239,
            "purplish red, red, purple, pink": 0xb0054b,
            "slime green, green": 0x99cc04,
            "baby poop, brown, green": 0x937c00,
            "irish green, green": 0x019529,
            "pink/purple, purple, pink": 0xef1de7,
            "dark navy, black, blue": 0x000435,
            "greeny blue, green, blue": 0x42b395,
            "light plum, purple, pink": 0x9d5783,
            "pinkish grey, purple, gray, pink, white": 0xc8aca9,
            "dirty orange, brown, yellow": 0xc87606,
            "rust red, red, brown": 0xaa2704,
            "pale lilac, purple, white, pink": 0xe4cbff,
            "orangey red, red, brown": 0xfa4224,
            "primary blue, blue": 0x0804f9,
            "kermit green, green": 0x5cb200,
            "brownish purple, brown": 0x76424e,
            "murky green, green": 0x6c7a0e,
            "wheat, yellow, white, brown": 0xfbdd7e,
            "very dark purple, black, purple, blue": 0x2a0134,
            "bottle green, green": 0x044a05,
            "watermelon, red": 0xfd4659,
            "deep sky blue, blue": 0x0d75f8,
            "fire engine red, red": 0xfe0002,
            "yellow ochre, yellow, brown": 0xcb9d06,
            "pumpkin orange, red, brown": 0xfb7d07,
            "pale olive, green, gray, white": 0xb9cc81,
            "light lilac, purple, white, pink": 0xedc8ff,
            "lightish green, green": 0x61e160,
            "carolina blue, blue, gray, white": 0x8ab8fe,
            "mulberry, purple, red": 0x920a4e,
            "shocking pink, pink": 0xfe02a2,
            "auburn, red, brown": 0x9a3001,
            "bright lime green, green": 0x65fe08,
            "celadon, green, white, gray": 0xbefdb7,
            "pinkish brown, brown, gray": 0xb17261,
            "poo brown, brown": 0x885f01,
            "bright sky blue, blue": 0x02ccfe,
            "celery, green, white": 0xc1fd95,
            "dirt brown, brown": 0x836539,
            "strawberry, red": 0xfb2943,
            "dark lime, green": 0x84b701,
            "copper, brown": 0xb66325,
            "medium brown": 0x7f5112,
            "muted green, green, gray": 0x5fa052,
            "robin's egg, blue, white": 0x6dedfd,
            "bright aqua, blue, white": 0x0bf9ea,
            "bright lavender, purple, pink": 0xc760ff,
            "ivory, yellow, white, gray": 0xffffcb,
            "very light purple, purple, pink, white, gray": 0xf6cefc,
            "light navy, blue, black, gray": 0x155084,
            "pink red, red": 0xf5054f,
            "olive brown, brown": 0x645403,
            "poop brown, brown": 0x7a5901,
            "mustard green, green, brown": 0xa8b504,
            "ocean green, green": 0x3d9973,
            "very dark blue, blue, black": 0x000133,
            "dusty green, green": 0x76a973,
            "light navy blue, blue, gray, black": 0x2e5a88,
            "minty green, green, white": 0x0bf77d,
            "adobe, brown, red, yellow": 0xbd6c48,
            "barney, purple, pink": 0xac1db8,
            "jade green, green": 0x2baf6a,
            "bright light blue, blue, white": 0x26f7fd,
            "light lime, green, white": 0xaefd6c,
            "dark khaki, brown, gray": 0x9b8f55,
            "orange yellow, yellow, brown": 0xffad01,
            "ocre, brown, gray": 0xc69c04,
            "maize, yellow, brown, white, gray": 0xf4d054,
            "faded pink, pink, purple": 0xde9dac,
            "british racing green, green": 0x05480d,
            "sandstone, brown, gray, white": 0xc9ae74,
            "mud brown, brown": 0x60460f,
            "light sea green, green, white, blue": 0x98f6b0,
            "robin egg blue, blue, white": 0x8af1fe,
            "aqua marine, green, blue": 0x2ee8bb,
            "dark sea green, green": 0x11875d,
            "soft pink, pink, purple": 0xfdb0c0,
            "orangey brown, brown": 0xb16002,
            "cherry red, red": 0xf7022a,
            "burnt yellow, yellow, brown": 0xd5ab09,
            "brownish grey, gray, brown, white": 0x86775f,
            "camel, brown": 0xc69f59,
            "purplish grey, purple, gray": 0x7a687f,
            "marine, blue, black": 0x042e60,
            "greyish pink, purple, pink, gray": 0xc88d94,
            "pale turquoise, green, white": 0xa5fbd5,
            "pastel yellow, yellow, white": 0xfffe71,
            "bluey purple, purple,": 0x6241c7,
            "canary yellow, yellow, white": 0xfffe40,
            "faded red, brown, red": 0xd3494e,
            "sepia, brown": 0x985e2b,
            "coffee, brown, gray": 0xa6814c,
            "bright magenta, pink": 0xff08e8,
            "mocha, brown, gray": 0x9d7651,
            "darker purple, purple, pink, blue, black":0x5f1b6b,
            "ecru, yellow, white": 0xfeffca,
            "purpleish, purple": 0x98568d,
            "cranberry, red, purple, pink": 0x9e003a,
            "darkish green, green": 0x287c37,
            "brown orange, brown": 0xb96902,
            "dusky rose, pink, purple": 0xba6873,
            "melon, red, brown": 0xff7855,
            "sickly green, green": 0x94b21c,
            "silver, gray, white": 0xc5c9c7,
            "purply blue, purply, blue": 0x661aee,
            "purpleish blue, blue": 0x6140ef,
            "hospital green, green, white": 0x9be5aa,
            "shit brown, brown, green": 0x7b5804,
            "mid blue, blue, gray": 0x276ab3,
            "amber, yellow, brown": 0xfeb308,
            "easter green, green, white": 0x8cfd7e,
            "soft blue, blue, gray": 0x6488ea,
            "cerulean blue, blue, gray": 0x056eee,
            "golden brown, brown": 0xb27a01,
            "bright turquoise, blue, white": 0x0ffef9,
            "red pink, pink, red": 0xfa2a55,
            "red purple, purple, red, brown": 0x820747,
            "greyish brown, brown, gray": 0x7a6a4f,
            "vermillion, red": 0xf4320c,
            "russet, red, brown, purple": 0xa13905,
            "steel grey, gray, white": 0x6f828a,
            "lighter purple, purple, pink": 0xa55af4,
            "bright violet, purple, pink": 0xad0afd,
            "prussian blue, blue, black, gray": 0x004577,
            "slate green, green, gray": 0x658d6d,
            "dirty pink, pink, gray": 0xca7b80,
            "dark blue green, green": 0x005249,
            "pine, green": 0x2b5d34,
            "yellowy green, green, white": 0xbff128,
            "dark gold, brown": 0xb59410,
            "bluish, blue, gray": 0x2976bb,
            "darkish blue, blue": 0x014182,
            "dull red, red, brown": 0xbb3f3f,
            "pinky red, red": 0xfc2647,
            "bronze, brown": 0xa87900,
            "pale teal, green, gray": 0x82cbb2,
            "military green, green": 0x667c3e,
            "barbie pink, pink": 0xfe46a5,
            "bubblegum pink, pink, white": 0xfe83cc,
            "pea soup green, green": 0x94a617,
            "dark mustard, brown": 0xa88905,
            "shit, brown": 0x7f5f00,
            "medium purple, purple, pink, gray": 0x9e43a2,
            "very dark green, green": 0x062e03,
            "dirt, brown": 0x8a6e45,
            "dusky pink, pink, purple, gray": 0xcc7a8b,
            "red violet, purple, red, pink": 0x9e0168,
            "lemon yellow, yellow, white": 0xfdff38,
            "pistachio, green, white": 0xc0fa8b,
            "dull yellow, yellow, brown, white, gray": 0xeedc5b,
            "dark lime green, green": 0x7ebd01,
            "denim blue, blue, gray": 0x3b5b92,
            "teal blue, blue, green, gray": 0x01889f,
            "lightish blue, blue": 0x3d7afd,
            "purpley blue, blue, purple": 0x5f34e7,
            "light indigo, purple, gray": 0x6d5acf,
            "swamp green, green": 0x748500,
            "brown green, green": 0x706c11,
            "dark maroon, red, brown, purple": 0x3c0008,
            "hot purple, pink, purple": 0xcb00f5,
            "dark forest green, black, green, blue": 0x002d04,
            "faded blue, blue, gray, white": 0x658cbb,
            "drab green, green, gray": 0x749551,
            "light lime green, green, white": 0xb9ff66,
            "snot greenl, green, gray": 0x9dc100,
            "yellowish, yellow, white, brown": 0xfaee66,
            "light blue green, green, blue, white": 0x7efbb3,
            "bordeaux, red, brown, purple": 0x7b002c,
            "light mauve, purple, pink, gray": 0xc292a1,
            "ocean, green, blue, gray": 0x017b92,
            "marigold, yellow, brown": 0xfcc006,
            "muddy green, green": 0x657432,
            "dull orange, yellow, brown": 0xd8863b,
            "steel, gray": 0x738595,
            "electric purple, purple, pink": 0xaa23ff,
            "fluorescent green, green, white": 0x08ff08,
            "yellowish brown, brown": 0x9b7a01,
            "blush, pink, red": 0xf29e8e,
            "soft green, green": 0x6fc276,
            "bright orange, red": 0xff5b00,
            "lemon, yellow, gray": 0xfdff52,
            "purple grey, gray, puprle": 0x866f85,
            "acid green, green, white": 0x8ffe09,
            "pale lavender, puprle, pink, white": 0xeecffe,
            "violet blue, blue black": 0x510ac9,
            "light forest green, green": 0x4f9153,
            "burnt red, red, brown": 0x9f2305,
            "khaki green, green, gray, yellow": 0x728639,
            "cerise, red, pink, purple": 0xde0c62,
            "darker blue, blue, black":0x011288,
            "faded purple, purple, gray, pink": 0x916e99,
            "apricot, yellow, brown": 0xffb16d,
            "dark olive green, green": 0x3c4d03,
            "grey brown, brown, gray": 0x7f7053,
            "green grey, green, gray": 0x77926f,
            "true blue, blue": 0x010fcc,
            "darker green, green":0x087804,
            "pale violet, purple, white, pink": 0xceaefa,
            "periwinkle blue, blue, purple, white, gray": 0x8f99fb,
            "light sky blue, white, blue": 0xc6fcff,
            "blurple, blue": 0x5539cc,
            "green brown, green, brown, gray": 0x544e03,
            "bluegreen, green, gray, blue": 0x017a79,
            "bright teal, green, white, blue": 0x01f9c6,
            "brownish yellow, yellow, brown": 0xc9b003,
            "pea soup, green, brown": 0x929901,
            "forest, green": 0x0b5509,
            "barney purple, pink, purple, red": 0xa00498,
            "ultramarine, blue": 0x2000b1,
            "purplish, purple, pink, gray": 0x94568c,
            "puke yellow, yellow, brown, green": 0xc2be0e,
            "bluish grey, grey": 0x748b97,
            "dark periwinkle, purple, blue, gray": 0x665fd1,
            "dark lilac, purple, gray, pink": 0x9c6da5,
            "reddish, red, brown": 0xc44240,
            "light maroon, red, brown, gray, pink": 0xa24857,
            "dusty purple, purple, pink, gray": 0x825f87,
            "terra cotta, red, brown": 0xc9643b,
            "avocado, green": 0x90b134,
            "marine blue, blue, black": 0x01386a,
            "teal green, green, blue": 0x25a36f,
            "slate grey, gray": 0x59656d,
            "lighter green, green, white": 0x75fd63,
            "electric green, green, white": 0x21fc0d,
            "dusty blue, blue, gray": 0x5a86ad,
            "golden yellow, yellow, brown": 0xfec615,
            "bright yellow, yellow, white": 0xfffd01,
            "light lavender, pink, purple, white": 0xdfc5fe,
            "umber, brown": 0xb26400,
            "poop, brown": 0x7f5e00,
            "dark peach, brown, red": 0xde7e5d,
            "jungle green, green": 0x048243,
            "eggshell, white, yellow": 0xffffd4,
            "denim, blue, gray, black": 0x3b638c,
            "yellow brown, brown, yellow, red": 0xb79400,
            "dull purple, purple, pink, gray": 0x84597e,
            "chocolate brown, brown, red": 0x411900,
            "wine red, red, brown": 0x7b0323,
            "neon blue, blue, white": 0x04d9ff,
            "dirty green, green": 0x667e2c,
            "light tan, yellow, white": 0xfbeeac,
            "ice blue, white, blue, gray": 0xd7fffe,
            "cadet blue, blue, gray": 0x4e7496,
            "dark mauve, purple, gray, pink, red": 0x874c62,
            "very light blue, white, blue, gray": 0xd5ffff,
            "grey purple, purple, gray, pink": 0x826d8c,
            "pastel pink, pink, purple, ": 0xffbacd,
            "very light green, green, white ": 0xd1ffbd,
            "dark sky blue, blue, gray, white": 0x448ee4,
            "evergreen, green, black": 0x05472a,
            "dull pink, pink, purple, gray, white": 0xd5869d,
            "aubergine, purple, red, brown, black": 0x3d0734,
            "mahogany, purple, red, brown, black": 0x4a0100,
            "reddish orange, red, brown": 0xf8481c,
            "deep green, green": 0x02590f,
            "vomit green, green, yellow": 0x89a203,
            "purple pink, pink, purple": 0xe03fd8,
            "dusty pink, pink, purple, gray, white": 0xd58a94,
            "faded green, green, gray, white": 0x7bb274,
            "camo green, green": 0x526525,
            "pinky purple, purple, pink": 0xc94cbe,
            "pink purple, pink": 0xdb4bda,
            "brownish red, red, brown": 0x9e3623,
            "dark rose, red, purple": 0xb5485d,
            "mud, brown, green": 0x735c12,
            "brownish, brown": 0x9c6d57,
            "emerald green, green": 0x028f1e,
            "pale brown, brown, gray, white": 0xb1916e,
            "dull blue, blue, gray, white": 0x49759c,
            "burnt umber, brown": 0xa0450e,
            "medium green, green": 0x39ad48,
            "clay, brown, gray, white": 0xb66a50,
            "light aqua, blue, white": 0x8cffdb,
            "light olive green, green, gray, white": 0xa4be5c,
            "brownish orange, brown, gray, white": 0xcb7723,
            "dark aqua, green": 0x05696b,
            "purplish pink, pink, red, purple": 0xce5dae,
            "dark salmon, red, brown": 0xc85a53,
            "greenish grey, gray, white, green": 0x96ae8d,
            "jade, green": 0x1fa774,
            "ugly green, green": 0x7a9703,
            "dark beige, brown, gray": 0xac9362,
            "emerald, green": 0x01a049,
            "pale red, red": 0xd9544d,
            "light magenta, pink, purple": 0xfa5ff7,
            "sky, blue, gray, white": 0x82cafc,
            "light cyan, blue, white": 0xacfffc,
            "yellow orange, yellow, brown": 0xfcb001,
            "reddish purple, red, purple": 0x910951,
            "reddish pink, red": 0xfe2c54,
            "orchid, purple, gray, pink": 0xc875c4,
            "dirty yellow, yellow, brown": 0xcdc50a,
            "orange red, red": 0xfd411e,
            "deep red, red, purple, brown": 0x9a0200,
            "orange brown, brown, red": 0xbe6400,
            "cobalt blue, blue, black": 0x030aa7,
            "neon pink, pink, purple": 0xfe019a,
            "rose pink, pink, purple": 0xf7879a,
            "greyish purple, gray, purple, white": 0x887191,
            "raspberry, red, purple": 0xb00149,
            "aqua green, green": 0x12e193,
            "salmon pink, red, pink, purple": 0xfe7b7c,
            "tangerine, yellow, brown": 0xff9408,
            "brownish green, green": 0x6a6e09,
            "red brown, brown, red": 0x8b2e16,
            "greenish brown, green": 0x696112,
            "pumpkin, brown, yellow": 0xe17701,
            "pine green, green": 0x0a481e,
            "charcoal, green, gray, black": 0x343837,
            "baby pink, pink, white, purple": 0xffb7ce,
            "cornflower, blue, gray, white": 0x6a79f7,
            "blue violet, purple, blue": 0x5d06e9,
            "chocolate, brown, black, red": 0x3d1c02,
            "greyish green, green, gray": 0x82a67d,
            "scarlet, red": 0xbe0119,
            "green yellow, green, yellow": 0xc9ff27,
            "dark olive, green, gray": 0x373e02,
            "sienna, brown": 0xa9561e,
            "pastel purple, purple ,pink, gray": 0xcaa0ff,
            "terracotta, brown, red": 0xca6641,
            "aqua blue, blue, white": 0x02d8e9,
            "sage green, green, gray": 0x88b378,
            "blood red, red, brown": 0x980002,
            "deep pink, pink, red": 0xcb0162,
            "grass, green": 0x5cac2d,
            "moss, green": 0x769958,
            "pastel blue, blue, gray, white": 0xa2bffe,
            "bluish green. green": 0x10a674,
            "green blue, green": 0x06b48b,
            "dark tan, brown": 0xaf884a,
            "greenish blue, green": 0x0b8b87,
            "pale orange, red, brown": 0xffa756,
            "vomit, green, brown": 0xa2a415,
            "forrest green, green": 0x154406,
            "dark lavender, purple, pink, gray": 0x856798,
            "dark violet, purple, red, black": 0x34013f,
            "purple blue, purple, blue": 0x632de9,
            "dark cyan, green, blue": 0x0a888a,
            "olive drab, green": 0x6f7632,
            "pinkish pink, red, pink": 0xd46a7e,
            "cobalt, blue, black": 0x1e488f,
            "neon purple, purple, pink": 0xbc13fe,
            "light turquoise, green, white, blue": 0x7ef4cc,
            "apple green, green": 0x76cd26,
            "dull green, green": 0x74a662,
            "wine, purple, red, purple": 0x80013f,
            "powder blue, blue, white, gray": 0xb1d1fc,
            "off white, white": 0xffffe4,
            "electric blue, blue": 0x0652ff,
            "dark turquoise, green": 0x045c5a,
            "blue purple, purple, blue": 0x5729ce,
            "azure, blue": 0x069af3,
            "bright red, red": 0xff000d,
            "pinkish red, red": 0xf10c45,
            "cornflower blue, blue, white, gray": 0x5170d7,
            "light olive, green, yellow": 0xacbf69,
            "grape, purple, red": 0x6c3461,
            "greyish blue, blue, gray": 0x5e819d,
            "purplish blue, purple, blue": 0x601ef9,
            "yellowish green, green": 0xb0dd16,
            "greenish yellow, green": 0xcdfd02,
            "medium blue, blue, gray": 0x2c6fbb,
            "dusty rose, red, pink, purple": 0xc0737a,
            "light violet, purple, pink, gray, white": 0xd6b4fc,
            "midnight blue, blue, black": 0x020035,
            "bluish purple, purple, pink": 0x703be7,
            "red orange, red": 0xfd3c06,
            "dark magenta, red, purple, pink": 0x960056,
            "greenish, green": 0x40a368,
            "ocean blue, blue, gray": 0x03719c,
            "coral, red": 0xfc5a50,
            "cream, yellow, white": 0xffffc2,
            "reddish brown, brown, red": 0x7f2b0a,
            "burnt sienna, brown": 0xb04e0f,
            "brick, brown, red": 0xa03623,
            "sage, green, gray, white": 0x87ae73,
            "grey green, green, gray, white": 0x789b73,
            "white, white, gray": 0xffffff,
            "robin's egg blue, blue, white": 0x98eff9,
            "moss green, green": 0x658b38,
            "steel blue, gray, blue": 0x5a7d9a,
            "eggplant, red, purple, black": 0x380835,
            "light yellow, yellow, white": 0xfffe7a,
            "leaf green, green": 0x5ca904,
            "light grey, gray, white": 0xd8dcd6,
            "puke, green, yellow": 0xa5a502,
            "pinkish purple, pink, purple": 0xd648d7,
            "sea blue, blue, gray": 0x047495,
            "pale purple, purple, pink": 0xb790d4,
            "slate blue, blue, gray, white": 0x5b7c99,
            "blue grey, blue, gray, white": 0x607c8e,
            "hunter green, green": 0x0b4008,
            "fuchsia, pink, purple": 0xed0dd9,
            "crimson, brown, red, purple": 0x8c000f,
            "pale yellow, yellow, white": 0xffff84,
            "ochre, brown, yellow": 0xbf9005,
            "mustard yellow, brown, yellow": 0xd2bd0a,
            "light red, red": 0xff474c,
            "cerulean, blue": 0x0485d1,
            "pale pink, pink, gray, puprle, white": 0xffcfdc,
            "deep blue, blue, black": 0x040273,
            "rust, brown, red": 0xa83c09,
            "light teal, green, whtie, gray": 0x90e4c1,
            "slate, gray, blue, white, black": 0x516572,
            "goldenrod, yellow, brown": 0xfac205,
            "dark yellow, yellow, brown": 0xd5b60a,
            "dark grey, green, gray, black": 0x363737,
            "army green, green, blue, gray, black": 0x4b5d16,
            "grey blue, blue, gray, white": 0x6b8ba4,
            "seafoam, green, white": 0x80f9ad,
            "puce, brown": 0xa57e52,
            "spring green, green": 0xa9f971,
            "dark orange, brown, red": 0xc65102,
            "sand, yellow, brown": 0xe2ca76,
            "pastel green, green, white": 0xb0ff9d,
            "mint, green, white": 0x9ffeb0,
            "light orange, brown, yellow, red": 0xfdaa48,
            "bright pink, pink, purple": 0xfe01b1,
            "chartreuse, green": 0xc1f80a,
            "deep purple, purple, black": 0x36013f,
            "dark brown, brown, black, red": 0x341c02,
            "taupe, brown, gray": 0xb9a281,
            "pea green, green": 0x8eab12,
            "puke green, green": 0x9aae07,
            "kelly green, green": 0x02ab2e,
            "seafoam green, green, white": 0x7af9ab,
            "blue green, green": 0x137e6d,
            "khaki, brown, white, green, gray": 0xaaa662,
            "burgundy, brown, purple, red": 0x610023,
            "dark teal, green": 0x014d4e,
            "brick red, red, purple, brown": 0x8f1402,
            "royal purple, purple, pink, blue": 0x4b006e,
            "plum, purple, brown, red": 0x580f41,
            "mint green, green, white": 0x8fff9f,
            "gold, yellow, brown": 0xdbb40c,
            "baby blue, blue, gray, white": 0xa2cffe,
            "yellow green, green": 0xc0fb2d,
            "bright purple, purple, pink": 0xbe03fd,
            "dark red, red, brown": 0x840000,
            "pale blue, white, blue, gray": 0xd0fefe,
            "grass green, green": 0x3f9b0b,
            "navy, black, blue": 0x01153e,
            "aquamarine, green, blue": 0x04d8b2,
            "burnt orange, red, brown": 0xc04e01,
            "neon green, green": 0x0cff0c,
            "bright blue, blue": 0x0165fc,
            "rose, red, pink": 0xcf6275,
            "light pink, pink, white": 0xffd1df,
            "mustard, yellow, brown": 0xceb301,
            "indigo, blue, black": 0x380282,
            "lime, green": 0xaaff32,
            "sea green, green": 0x53fca1,
            "periwinkle, purple, gray, pink": 0x8e82fe,
            "dark pink, pink, red": 0xcb416b,
            "olive green, green": 0x677a04,
            "peach, red, yellow, brown": 0xffb07c,
            "pale green, green, white": 0xc7fdb5,
            "light brown, brown": 0xad8150,
            "hot pink, pink": 0xff028d,
            "black": 0x000000,
            "lilac, purple, pink, gray": 0xcea2fd,
            "navy blue, blue, black": 0x001146,
            "royal blue, blue": 0x0504aa,
            "beige, brown, yellow, white": 0xe6daa6,
            "salmon, red, brown": 0xff796c,
            "olive, green": 0x6e750e,
            "maroon, red, brown, purple": 0x650021,
            "bright green, green": 0x01ff07,
            "dark purple, purple, black, red": 0x35063e,
            "mauve, pink, purple, gray": 0xae7181,
            "forest green, green": 0x06470c,
            "aqua, blue, green": 0x13eac9,
            "cyan, blue, white": 0x00ffff,
            "tan, yellow, brown": 0xd1b26f,
            "dark blue, blue, black": 0x00035b,
            "lavender, purple, pink": 0xc79fef,
            "turquoise, green, blue": 0x06c2ac,
            "dark green, green": 0x033500,
            "violet, purple, pink": 0x9a0eea,
            "light purple, purple, pink": 0xbf77f6,
            "lime green, green": 0x89fe05,
            "grey, gray, white": 0x929591,
            "sky blue, blue, gray, white": 0x75bbfd,
            "yellow, yellow": 0xffff14,
            "magenta, pink, red, purple": 0xc20078,
            "light green, green, white": 0x96f97b,
            "orange, red, brown": 0xf97306,
            "teal, green": 0x029386,
            "light blue, blue, whtie, gray": 0x95d0fc,
            "red": 0xe50000,
            "brown": 0x653700,
            "pink": 0xff81c0,
            "blue": 0x0343df,
            "green": 0x15b01a,
            "purple": 0x7e1e9c
            ]
             
                          
                    
    static let colorMapKor :[String:Int] = [
        "빨강":0xd73522,
        "주황":0xea9b39,
        "갈색":0x5d2c16,
        "노랑":0xfdea54,
        "연두":0xaece3a,
        "초록":0x3a844a,
        "파랑":0x3d98f1,
        "분홍":0xe7b5dc,
        "자주":0x9c2258,
        "보라":0x3c1381,
        "청록":0x3d8ea1,
        "남색":0x133487,
        "회색":0x7C7C7C,
        "검정":0x434343,
        //            "옅은",
        //            "진한",
        "하양":0xf4f4f4,
        "투명":0x6AF4F4
    ]
    
    static let colorIndex :[String:Int] = [
        "빨강":0,
        "주황":1,
        "갈색":2,
        "노랑":3,
        "연두":4,
        "초록":5,
        "파랑":6,
        "분홍":7,
        "자주":8,
        "보라":9,
        "청록":10,
        "남색":11,
        "회색":12,
        "검정":13,
        
        "하양":14,
        "투명":15
    ]
                          


    class func colorConvert(fromRGBFloat rgbValue: Int) -> UIColor? {
        return UIColor(
            red: CGFloat((Float((rgbValue & 0xff0000) >> 16)) / 255.0
                         ),
            green: CGFloat((Float((rgbValue & 0xff00) >> 8)) / 255.0),
            blue: CGFloat((Float(rgbValue & 0xff)) / 255.0),
            alpha: 1.0)
    }
   
    class func name(for color: UIColor) -> String? {

       
        var iR: CGFloat = 0
        var iG: CGFloat = 0
        var iB: CGFloat = 0
        var iA: CGFloat = 0

        color.getRed(&iR, green: &iG, blue: &iB, alpha: &iA)
        

        var minDistance = CGFloat.greatestFiniteMagnitude
        var colorKey: String = ""

        
        
        for (key, _) in colorMap {
          
            if let currentColor = colorMap[key] {
    //            print(color)
                var cR: CGFloat = 0
                var cG: CGFloat = 0
                var cB: CGFloat = 0
                var cA: CGFloat = 0
                
                
                
                
                UIColor(rgb: currentColor).getRed(&cR, green: &cG, blue: &cB, alpha: &cA)
                let dR = iR - cR
                let dG = iG - cG
                let dB = iB - cB

                let a = pow(dR, 2.0)
                let b = pow(dG, 2.0)
                let c = pow(dB, 2.0)

                let d = sqrt(a + b + c)

                if d < minDistance {
                    minDistance = d
                    colorKey = key
                }
            }

               
            
        }
        return colorKey
    }
    
    
    class func getListOfColorInKorean(eng_color:String) -> [String]{
        let map: [String : [String]] = [
            "white": ["하양"],
            "red": ["빨강", "주황", "자주","갈색"],
            "yellow": ["노랑", "주황"],
            "brown": ["갈색", "노랑", "주황"],
            "pink": ["분홍", "자주", "보라"],
            "green": ["초록", "청록", "연두"],
            "gray": ["진한", "회색"],
            "purple": ["자주", "보라"],
            "blue": ["파랑", "청록", "남색"],
            "black": ["검정", "남색"]
        ]
        
        return map[eng_color.lowercased()] ?? []
    }
    
    
    class func getListOfColorInKoreanFromEngList(color:String) -> [String]{
        let _color = color.replacingOccurrences(of: " ", with: "")
        let splited = _color.split(separator: ",")
        
        var color_list : [String] = []
//        var count = 0
//        print("extract color")
        for c in splited {
            //print(c)
            
//            print("\(count) : \(c)")
            let colors_kor = getListOfColorInKorean(eng_color: String(c))
            
            for kor in  colors_kor {
                if !color_list.contains(kor) {
                    color_list.append(kor)
                }
            }
        }
        
        return color_list
    }
    
    
}
